site_name: Ukrainian IT Communities
repo_url: https://github.com/nikit0ns/Ukrainian_IT_Communities
repo_name: nikit0ns/Ukrainian_IT_Communities
theme:
  name: material
  logo: assets/icon.png
  favicon: assets/icon.png
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.integrate
  palette:
    - scheme: default
      primary: white
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/brightness-3
        name: Switch to light mode

extra:
  social:
    - icon: fontawesome/brands/mastodon 
      link: https://fosstodon.org/@squidfunk
